config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'projects#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :projects, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :review
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, length: {minimum: 3}, uniqueness: true
    has_many :reviews, dependent: :destroy
    belongs_to :user

    delegate :email, to: :user

    def average_rating
      return 'N/A' if reviews.none?
      reviews.average(:rating)
    end

end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)

  belongs_to :project
  belongs_to :user

  has_many :endorsements

  delegate :email, to: :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

   has_many :projects
   has_many :reviews
   
   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  # rescue_from Pundit::NotAuthorizedError do
  # redirect_to root_url, alert: "You do not have access to this page"
  # end
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  # def new
  #   @review = Review.find(params[:review_id])
  #     if @review.user_id == current_user.id
  #       flash[:notice] = 'you cannot endorse your own review.'
  #       redirect_to projects_path
  #     else
  #       @review.endorsements.create
  #       redirect_to projects_path
  #     end
  #   end

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, :except => [:index]

  def index
    @projects = Project.all
  end

  def new
    authenticate_user!
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
      if @project.save
        redirect_to projects_path
      else
        render 'new'
    end
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
    if current_user.id != @project.user_id
      flash[:notice] = "you cannot edit somebody else's project."
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def update
    @project = Project.find(params[:id])
      if current_user.id != @project.user_id
      flash[:notice] = "you cannot edit somebody else's project."
      redirect_to projects_path
    else
      @project.update(project_params)
      flash[:notice] = 'Project edited successfully'
      redirect_to projects_path
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if current_user.id != @project.user_id
      flash[:notice] = "you cannot delete somebody else's project."
      redirect_to projects_path
    else
      @project.destroy
      flash[:notice] = 'Project deleted successfully'
      redirect_to projects_path
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @project = Project.find(params[:project_id])
      if @project.reviews.find_by user_id: current_user
        flash[:notice] = 'you cannot review the same project twice.'
        redirect_to projects_path
      elsif user_signed_in?
        @review = Review.new
      else
        flash[:notice] = "you need to be logged in to leave a review."
        redirect_to projects_path
    end
  end

  def create
    @project = Project.find params[:project_id]
    @review = @project.reviews.new params[:review].permit(:thoughts, :rating)
      if @project.reviews.find_by user_id: current_user
        flash[:notice] = 'you cannot review the same project twice.'
        redirect_to projects_path
      else
        @review.user = current_user
        @review.save
        flash[:notice] = "you've successfully left a review!"
        redirect_to projects_path
      end
    end

  def destroy
    # @project = Project.find(params[:project_id])
    @review = Review.find(params[:id])
    # @review.find_by(:id, current_user)
      if 
        @review.user != current_user
        flash[:notice] = "you cannot delete somebody else's review!"
        redirect_to projects_path
      else
        @review.destroy
        flash[:notice] = 'Review deleted successfully'
        redirect_to projects_path
      end
  end

# private
  # def review_params
  #   params.require(:review).permit(:id, :project_id, :thoughts, :rating)
  # end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
  end
end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    '★' * rating.round + '☆' * remainder
  end

end

app/views/layouts/_alerts.html.erb
<%= notice %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>

  <%= link_to 'home', root_path %>
  <%= link_to 'projects', projects_path %>
  <%=t 'greet_user', email: current_user.email %>
  <%= link_to 'log out', destroy_user_session_path, method: :delete %>

<% else %>
  
  <%= link_to 'log in with Facebook', user_facebook_omniauth_authorize_path %>
  <%= link_to 'log in', new_user_session_path %>
  <%= link_to 'sign up', new_user_registration_path %>
  
<% end %>

<h1>TestCrowd.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestCrowd</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

  <%= render "layouts/header" %>
  <%= render "layouts/alerts" %>

  <%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<%= form_for @project do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "update project" %>

<% end %>

app/views/projects/index.html.erb
<% if user_signed_in? %>


  <% if @projects.any? %>
  <p>projects that are currently live:</p>
    <% @projects.each do |project| %>
      <h2> <%= link_to project.name, project_path(project) %> </h2>
      <% if user_signed_in? %>
        <%= link_to "edit #{project.name}", edit_project_path(project) %>
        <%= link_to "delete #{project.name}", project_path(project), method: :delete %>
      <% end %>
      <%=link_to "review #{project.name}", new_project_review_path(project) %>
    <h3>Reviews for <%= project.name %></br>
        average rating: <%= star_rating project.average_rating.to_i %></h3>
      <% if project.reviews.any? %>
        <ul>
          <% project.reviews.each do |review| %>
           <li>
            <%= review.thoughts %>, <strong><%= star_rating review.rating %></strong>
            <%=link_to "endorse review", review_endorsements_path(review) , class: 'endorsements-link' %>
            <span class='endorsements_count'> <%= review.endorsements.count %></span> <%= 'endorsement'.pluralize(review.endorsements.count) %>
          </li> 
          <% end %>
        </ul>
      <% else %>
        <p>No reviews yet!</p>
      <% end %>
    <% end %>

    <% else %>
      no projects yet!
  <% end %>

    <%=link_to "add a project", new_project_path if current_user.admin? %>


    <% else %>

<p>Please join our community to test your campaign before it goes live.</p>

<% end %>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
  <section id="errors">
    <h2> <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved: </h2>
    <ul>
      <% @project.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @project do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit "create project" %>

<% end %>

app/views/projects/show.html.erb
<p><strong><%= @project.name %></strong> - added by <%= @project.email %></p>
<p>average rating: <%= star_rating @project.average_rating.to_i %></p>
<p><%= @project.description %></p>

  <% if @project.reviews.any? %>
    <ul>
      <% @project.reviews.each do |review| %>
      <li>
        <%= review.thoughts %>, <strong><%= star_rating review.rating %></strong> 
        <%= link_to "delete review", review_path(review), method: :delete %></p>
        <p>review by <%= review.email %>
      </li>
      <% end %>
    </ul>
    <% else %>
      <p>No reviews yet!</p>
  <% end %>

app/views/reviews/new.html.erb
<%= form_for [@project, @review] do |f| %>
	<%= f.label :thoughts %>
	<%= f.text_area :thoughts %>
	<%= f.label :rating %>
	<%= f.select :rating, (1..5) %>
	<%= f.submit 'leave review' %>
<% end %>